# Generated by Django 5.1 on 2025-07-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='adhhd', max_length=500),
            preserve_default=False,
        ),
    ]
